export const INITIALIZE = 'INITIALIZE';
export const SETDATA = 'SETGDATA';
export const SETACTIVEPOST = 'SETACTIVEPOST';
export const SETCURRENTPOST = 'SETCURRENTPOST';
export const SETPAGETYPE = 'SETPAGETYPE';